version: '3'
services:
  #************Mongo DB***************
  database_mongo:
    container_name: mongo_container
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_DATABASE=TWEET_APP_METADATA
#    volumes:
#      - ./mongodb_data_container:/data/db
      #means you want to set data on container persist on your local folder named mongo-volume . /data/db/ is a folder that already created inside the mongo container.
    ports:
      - 27017:27017
  #************Backend***************
  backend_spring:
    container_name: spring_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - database_mongo
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: zoo_container
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock